CREATE VIEW [dbo].[Event_Jour]
	AS SELECT Current_OF, Code, Etat, CAST(Heure_Event AS TIME(0)) AS 'Heure_Event'
	FROM dbo.QAGATE_1_EventData
	WHERE (Heure_Event > CAST(CAST(DATEADD(HOUR, -6, GETDATE()) AS DATE) AS DATETIME) + CAST('06:00:00' AS DATETIME)) AND (Heure_Event < CAST(CAST(DATEADD(HOUR, 18, GETDATE()) AS DATE) AS DATETIME) + CAST('06:00:00' AS DATETIME))